---


- name: Restart tunnel
  ansible.builtin.service:
    name: wg-quick@wg0
    state: restarted

# Workaround: use wgclient1 statically as loop_var cannot be used here
- name: Restart peer tunnel
  ansible.builtin.service:
    name: "wg-quick@wgclient1"
    state: restarted



